AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BucketName:
    Type: String
  BucketKeyEnabled:
    Type: String
  VersioningStatus:
    Type: String
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
          Status: !Ref VersioningStatus
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - BucketKeyEnabled: !Ref BucketKeyEnabled
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True  
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Deny
            Action:
              - 's3:*'          
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}"
              - !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal: '*'
            Condition:
              Bool:
                'aws:SecureTransport': "false"