AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  BucketName:
    Type: String
  BucketKeyEnabled:
    Type: String
  VersioningStatus:
    Type: String
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
          Status: String
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionRule:
              BucketKeyEnabled: !Ref BucketKeyEnabled